<a href="https://colab.research.google.com/github/tanishjain-tmj/House-Price-Predictor-Ml/blob/main/House_Price_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project House Price Predictor

In [2]:
import pandas as pd
import numpy as np

In [3]:
house = pd.read_csv('/content/Bengaluru_House_Data (1).csv')

In [4]:
house.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
house.shape

(13320, 9)

In [6]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [7]:
# creating backup copy
backup = house.copy()

In [8]:
# checking missing values
house.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [9]:
# removing society because it has many missing values
house.drop('society', axis=1, inplace=True)

In [10]:
# removing remaining missing values
house = house.dropna()

In [11]:
house = house.reset_index(drop=True)

In [12]:
house.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [13]:
#data type cleaning
house.dtypes

area_type        object
availability     object
location         object
size             object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object

In [14]:
# extracting BHK from size
house['BHK'] = house['size'].str.extract(r'(\d+)').astype(float)

In [15]:
house[['size', 'BHK']].head()

        size  BHK
0      2 BHK  2.0
1  4 Bedroom  4.0
2      3 BHK  3.0
3      3 BHK  3.0
4      2 BHK  2.0

In [16]:
house.drop('size', axis=1, inplace=True)

In [17]:
#clean total_sqft
def convert_sqft(x):
    try:
        if '-' in str(x):
            a, b = str(x).split('-')
            return (float(a) + float(b)) / 2
        else:
            return float(x)
    except:
        return np.nan

In [18]:
house['total_sqft'] = house['total_sqft'].apply(convert_sqft)

In [19]:
house.isnull().sum()

area_type        0
availability     0
location         0
total_sqft      42
bath             0
balcony          0
price            0
BHK              0
dtype: int64

In [21]:
house = house.dropna()

In [22]:
house = house.reset_index(drop=True)

In [23]:
#target column
house.rename(columns={'price': 'Price'}, inplace=True)

In [24]:
house.head()

,area_type,availability,location,total_sqft,bath,balcony,Price,BHK
0,Super built-up Area,19-Dec,Electronic City Phase II,1056.0,2.0,1.0,39.07,2.0
1,Plot Area,Ready To Move,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4.0
2,Built-up Area,Ready To Move,Uttarahalli,1440.0,2.0,3.0,62.00,3.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3.0
4,Super built-up Area,Ready To Move,Kothanur,1200.0,2.0,1.0,51.00,2.0

In [25]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12668 entries, 0 to 12667
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12668 non-null  object
 1   availability  12668 non-null  object
 2   location      12668 non-null  object
 3   total_sqft    12668 non-null  float64
 4   bath          12668 non-null  float64
 5   balcony       12668 non-null  float64
 6   Price         12668 non-null  float64
 7   BHK           12668 non-null  float64
dtypes: float64(5), object(3)
memory usage: 791.9+ KB

In [26]:
#Outlier removal
house['Price'].describe()

count    12668.000000
mean       105.952648
std        131.813137
min          8.000000
25%         49.015000
50%         70.000000
75%        115.000000
max       2912.000000
Name: Price, dtype: float64

In [27]:
Q1 = house['Price'].quantile(0.25)
Q3 = house['Price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

house = house[
    (house['Price'] >= lower) &
    (house['Price'] <= upper)
]

In [28]:
house = house.reset_index(drop=True)

In [29]:
house.head()

,area_type,availability,location,total_sqft,bath,balcony,Price,BHK
0,Super built-up Area,19-Dec,Electronic City Phase II,1056.0,2.0,1.0,39.07,2.0
1,Plot Area,Ready To Move,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4.0
2,Built-up Area,Ready To Move,Uttarahalli,1440.0,2.0,3.0,62.00,3.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3.0
4,Super built-up Area,Ready To Move,Kothanur,1200.0,2.0,1.0,51.00,2.0

In [30]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11513 entries, 0 to 11512
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     11513 non-null  object
 1   availability  11513 non-null  object
 2   location      11513 non-null  object
 3   total_sqft    11513 non-null  float64
 4   bath          11513 non-null  float64
 5   balcony       11513 non-null  float64
 6   Price         11513 non-null  float64
 7   BHK           11513 non-null  float64
dtypes: float64(5), object(3)
memory usage: 719.7+ KB

In [31]:
house.describe(include='all')

,area_type,availability,location,total_sqft,bath,balcony,Price,BHK
count,11513,11513,11513,11513.00000,11513.000000,11513.000000,11513.000000,11513.000000
unique,4,78,1173,NaN,NaN,NaN,NaN,NaN
top,Super built-up Area,Ready To Move,Whitefield,NaN,NaN,NaN,NaN,NaN
freq,8041,9045,441,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,1352.31340,2.454009,1.561626,76.832029,2.599236
std,NaN,NaN,NaN,899.32752,1.007783,0.798959,40.802282,1.019480
min,NaN,NaN,NaN,5.00000,1.000000,0.000000,8.000000,1.000000
25%,NaN,NaN,NaN,1075.00000,2.000000,1.000000,47.000000,2.000000
50%,NaN,NaN,NaN,1230.00000,2.000000,2.000000,65.000000,2.000000
75%,NaN,NaN,NaN,1527.00000,3.000000,2.000000,95.000000,3.000000
max,NaN,NaN,NaN,52272.00000,15.000000,3.000000,213.000000,14.000000

In [32]:
house.to_csv(
    'Cleaned_House_data.csv',
    index=False
)

In [33]:
# extracting training data
X = house.drop('Price', axis=1)
Y = house['Price']

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [35]:
categorical_cols = X.select_dtypes(
    include='object'
).columns

categorical_cols

Index(['area_type', 'availability', 'location'], dtype='object')

In [36]:
numerical_cols = X.select_dtypes(
    include=np.number
).columns

numerical_cols

Index(['total_sqft', 'bath', 'balcony', 'BHK'], dtype='object')

In [61]:
#model building
#onehotencoder
from sklearn.preprocessing import OneHotEncoder

one = OneHotEncoder(
    handle_unknown='ignore'
)

In [62]:
#column transformer
from sklearn.compose import make_column_transformer

column_trans = make_column_transformer(
    (one, categorical_cols),
    remainder='passthrough'
)

In [63]:
#linear regression
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [64]:
#pipeline
from sklearn.pipeline import make_pipeline

pipe = make_pipeline(
    column_trans,
    lr
)

In [65]:
#fit the model
pipe.fit(X_train, Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['area_type', 'availability', 'location'], dtype='object'))])),
                ('linearregression', LinearRegression())])

In [67]:
#predction
Y_pred = pipe.predict(X_test)

In [68]:
#r2 score
from sklearn.metrics import r2_score

r2_score(Y_test, Y_pred)

0.6074544915850184

In [69]:
#find best random state
scores = []

for i in range(1000):

    X_train, X_test, Y_train, Y_test = train_test_split(
        X,
        Y,
        test_size=0.2,
        random_state=i
    )

    lr = LinearRegression()

    pipe = make_pipeline(
        column_trans,
        lr
    )

    pipe.fit(X_train, Y_train)

    Y_pred = pipe.predict(X_test)

    scores.append(
        r2_score(Y_test, Y_pred)
    )

In [45]:
np.argmax(scores)

np.int64(394)

In [46]:
scores[np.argmax(scores)]

0.6074544915850184

In [47]:
best_random_state = np.argmax(scores)

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=best_random_state
)

In [48]:
lr = LinearRegression()

pipe = make_pipeline(
    column_trans,
    lr
)

pipe.fit(X_train, Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['area_type', 'availability', 'location'], dtype='object'))])),
                ('linearregression', LinearRegression())])

In [55]:
from sklearn.metrics import r2_score
Y_pred = pipe.predict(X_test)
print("R2 Score:", r2_score(Y_test, Y_pred))

R2 Score: 0.6074544915850184

In [60]:
# Taking house details from user

area_type = input("Enter Area Type: ")
availability = input("Enter Availability: ")
location = input("Enter Location: ")

total_sqft = float(input("Enter Total Square Feet: "))
bath = float(input("Enter Number of Bathrooms: "))
balcony = float(input("Enter Number of Balconies: "))
BHK = float(input("Enter Number of BHK: "))


# Create input data

input_data = pd.DataFrame({
    'area_type': [area_type],
    'availability': [availability],
    'location': [location],
    'total_sqft': [total_sqft],
    'bath': [bath],
    'balcony': [balcony],
    'BHK': [BHK]
})


# Predict house price

predicted_price = pipe.predict(input_data)


print("Predicted House Price:", predicted_price[0], "Lakhs")

Enter Area Type: super built up area
Enter Availability: ready to move
Enter Location: whitefield
Enter Total Square Feet: 1200
Enter Number of Bathrooms: 2
Enter Number of Balconies: 1
Enter Number of BHK: 2
Predicted House Price: 73.15139609649412 Lakhs